import { Imobile } from "../model/mobile";


export let mobileProducts : Array<Imobile>= [{
      id: 1,
      name: 'iPhone 13',
      brand: 'Apple',
      price: 999,
      offerprice:1999,
      image: 'https://i.insider.com/6116b065c040ad0018ce3ea1?width=1009&format=jpeg',
      isAvailable: true,
      rating: 4.9,
      noOfItems: 50,
      specification : ["Ram 16", "Camera 64mp", "256 GB"],
      details:["128 GB ROM",
        "15.49 cm (6.1 inch) Super Retina XDR Display",
        "48MP + 12MP | 12MP Front Camera",
        "A16 Bionic Chip, 6 Core Processor Processor"]
      
    },
    {
      id: 2,
      name: 'Samsung Galaxy S21',
      brand: 'Samsung',
      price: 899,
      offerprice:1999,
      image: '',
      isAvailable: false,
      rating: 4.5,
      noOfItems: 20,
      specification : ["Ram 16", "Camera 64mp", "256 GB"],
      details:["128 GB ROM",
        "15.49 cm (6.1 inch) Super Retina XDR Display",
        "48MP + 12MP | 12MP Front Camera",
        "A16 Bionic Chip, 6 Core Processor Processor"]
    },
    {
      id: 3,
      name: 'Google Pixel 6',
      brand: 'Google',
      price: 799,
      offerprice:1999,
      image: 'https://support.apple.com/library/content/dam/edam/applecare/images/en_US/iOS/ios16-iphone13-pro-widgets-home-screen.png',
      isAvailable: false,
      rating: 3.9,
      noOfItems: 10,
      specification : ["Ram 16", "Camera 64mp", "256 GB"],
      details:["128 GB ROM",
        "15.49 cm (6.1 inch) Super Retina XDR Display",
        "48MP + 12MP | 12MP Front Camera",
        "A16 Bionic Chip, 6 Core Processor Processor"]
    },
    {
      id: 4,
      name: 'OnePlus 9 Pro',
      brand: 'OnePlus',
      price: 899,
      offerprice:1999,
      image: '',
      isAvailable: true,
      rating: 2.9,
      noOfItems: 7,
      specification : ["Ram 16", "Camera 64mp", "256 GB"],
      details:["128 GB ROM",
        "15.49 cm (6.1 inch) Super Retina XDR Display",
        "48MP + 12MP | 12MP Front Camera",
        "A16 Bionic Chip, 6 Core Processor Processor"]
    },
    {
      id: 5,
      name: 'Xiaomi Mi 11',
      brand: 'Xiaomi',
      price: 699,
      offerprice:1999,
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_RzdvwZ2YQZDdcxwdHPXPk9hRMqtaX3ZbSA&usqp=CAU',
      isAvailable: true,
      rating: 4.8,
      noOfItems: 5,
      specification : ["Ram 16", "Camera 64mp", "256 GB"],
      details:["128 GB ROM",
        "15.49 cm (6.1 inch) Super Retina XDR Display",
        "48MP + 12MP | 12MP Front Camera",
        "A16 Bionic Chip, 6 Core Processor Processor"]
    },
    {
      id: 6,
      name: 'Sony Xperia 1 III',
      brand: 'Sony',
      price: 1199,
      offerprice:1999,
      image: '',
      isAvailable: true,
      rating: 2.5,
      noOfItems: 100,
      specification : ["Ram 16", "Camera 64mp", "256 GB"],
      details:["128 GB ROM",
        "15.49 cm (6.1 inch) Super Retina XDR Display",
        "48MP + 12MP | 12MP Front Camera",
        "A16 Bionic Chip, 6 Core Processor Processor"]
    },
    {
      id: 7,
      name: 'LG Velvet',
      brand: 'LG',
      price: 599,
      offerprice:1999,
      image: '',
      isAvailable: false,
      rating: 1.5,
      noOfItems: 2,
      specification : ["Ram 16", "Camera 64mp", "256 GB"],
      details:["128 GB ROM",
        "15.49 cm (6.1 inch) Super Retina XDR Display",
        "48MP + 12MP | 12MP Front Camera",
        "A16 Bionic Chip, 6 Core Processor Processor"] 
    },
    {
      id: 8,
      name: 'Huawei P40 Pro',
      brand: 'Huawei',
      price: 899,
      offerprice:1999,
      image: '',
      isAvailable: true,
      rating: 3.5,
      noOfItems: 45,
      specification : ["Ram 16", "Camera 64mp", "256 GB"],
      details:["128 GB ROM",
        "15.49 cm (6.1 inch) Super Retina XDR Display",
        "48MP + 12MP | 12MP Front Camera",
        "A16 Bionic Chip, 6 Core Processor Processor"]
    },
    {
      id: 9,
      name: 'Motorola Moto G Power',
      brand: 'Motorola',
      price: 249,
      offerprice:1999,
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_RzdvwZ2YQZDdcxwdHPXPk9hRMqtaX3ZbSA&usqp=CAU',
      isAvailable: true,
      rating: 4.5,
      noOfItems: 500,
      specification : ["Ram 16", "Camera 64mp", "256 GB"],
      details:["128 GB ROM",
        "15.49 cm (6.1 inch) Super Retina XDR Display",
        "48MP + 12MP | 12MP Front Camera",
        "A16 Bionic Chip, 6 Core Processor Processor"]
    },
    {
      id: 10,
      name: 'Nokia 8.3',
      brand: 'Nokia',
      price: 499,
      offerprice:1999,
      image: '',
      isAvailable: true,
      rating: 4.5,
      noOfItems: 8,
      specification : ["Ram 16", "Camera 64mp", "256 GB"],
      details:["128 GB ROM",
        "15.49 cm (6.1 inch) Super Retina XDR Display",
        "48MP + 12MP | 12MP Front Camera",
        "A16 Bionic Chip, 6 Core Processor Processor"]
    }
  ];